version: "3.8"

services:

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - database:/data/
    ports:
    - "5432:5432"


  user_app:
    container_name: authorization
    build:
      ./
    links:
      - database
    command: uvicorn main:user --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"


volumes:
  database: