version: "3.8"

services:

  user_app:
    container_name: user
    build:
      ./
    command: uvicorn main:user --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - sql
      - nginx


networks:
    sql:
      external: true
    nginx:
      external: true

volumes:
  database: