name: "Python CI"
on:

  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker network
        run: docker network create sql
      - name: Build docker container
        run: docker-compose up -d
      - name: Check running containers
        run: docker ps -a

  Linter:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker network
        run: docker network create sql
      - name: Build docker container
        run: docker-compose up -d
      - name: Check code by linter
        run: docker exec authorization ruff check
